springfox.documentation.swagger.v2.path: /api-docs
server.port: 8080
spring.jackson:
    date-format: it.openapigenerator.theclassifier.inokers.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
datasets:
  iris:
    train: src/main/resources/datasets/iris/iris_for_train.arff
    test: src/main/resources/datasets/iris/iris_for_test.arff
weka:
  tree:
    j48:
      unpruned-option: -U
